version: "3.5"

services:
  loganalyzer:
    image: loganalyzer:latest
    container_name: loganalyzer
    build:
      context: .
    volumes:
      - ./logapp/:/loganalyzer/logapp/:z
      - loganalyzer-media:/loganalyzer/media
    ports:
      - 8080:8000
    env_file:
      - ./logapp/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: loganalyzer-postgres
    volumes:
      - psql-data:/var/lib/postgresql/data
    env_file:
      - ./logapp/.env

  adminer:
    image: adminer:latest
    container_name: loganalyzer-adminer
    ports:
      - 8082:8080
    env_file:
      - ./logapp/.env

volumes:
  psql-data:
  loganalyzer-media:

