services:
  loganalyzer:
    image: loganalyzer:latest
    container_name: loganalyzer
    build:
      context: .
    volumes:
      - ./logapp/:/loganalyzer/logapp/:z
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: loganalyzer-postgres
    volumes:
      - psql-data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: loganalyzer-adminer
    ports:
      - 8082:8080
    env_file:
      - .env

volumes:
  psql-data:
  loganalyzer-media:
